[credentials]

  [credentials.admin]
  username = "labcav"
  password = "cavcav690"
  role     = "admin"

  [credentials.profesor]
  username = "cav"
  password = "profesor123"
  role     = "profesor"
