[credentials]

  [credentials.admin]
  username = "cav"
  password = "cavcav690"
  role     = "admin"
    
  [credentials.profesor]
  username = "profe"
  password = "profesor123"
  role     = "profesor"
